@startuml ch3_use_case_global

left to right direction

skinparam backgroundColor #E8F0E2
skinparam defaultFontName Arial
skinparam defaultFontSize 11
skinparam shadowing false
skinparam roundcorner 12
skinparam actorStyle awesome

skinparam ArrowColor #555555

skinparam actor {
    BorderColor #444444
    FontColor black
    BackgroundColor transparent
}

skinparam usecase {
    BackgroundColor #F5F7F2
    BorderColor #444444
    FontColor black
}

skinparam rectangle {
    BackgroundColor #DDE8D8
    BorderColor transparent
}

title <size:18><b>Plateforme LLM Dashboard</b></size>

actor "Administrateur" as ADMIN
actor "Administrateur\nTenant" as TENANT
actor "Observateur" as OBS
actor "Agent\nApplicatif" as AGENT

rectangle "LLM Dashboard Platform" {

    usecase "S’authentifier" as AUTH

    usecase "Consulter\nDashboard" as DASH
    usecase "Consulter\nAnalytics" as ANALYTICS
    usecase "Consulter\nAnomalies IA" as ANOMALY

    usecase "Gérer\nUtilisateurs" as USERS
    usecase "Gérer\nClés API" as APIKEYS
    usecase "Configurer\nGouvernance" as GOV

    usecase "Envoyer\nAppels LLM" as LLM

    usecase "Gérer\nFacturation" as BILLING
    usecase "Tracer\nSessions LLM" as SESSION
    usecase "Gérer\nPrompts" as PROMPTS
}

ADMIN --> USERS
ADMIN --> BILLING

TENANT --> DASH
TENANT --> ANALYTICS
TENANT --> ANOMALY
TENANT --> APIKEYS
TENANT --> GOV
TENANT --> SESSION
TENANT --> PROMPTS

OBS --> DASH
OBS --> ANALYTICS
OBS --> ANOMALY

AGENT --> LLM

DASH ..> AUTH : <<include>>
ANALYTICS ..> AUTH : <<include>>
ANOMALY ..> AUTH : <<include>>
USERS ..> AUTH : <<include>>
APIKEYS ..> AUTH : <<include>>
GOV ..> AUTH : <<include>>
BILLING ..> AUTH : <<include>>
SESSION ..> AUTH : <<include>>
PROMPTS ..> AUTH : <<include>>
LLM ..> AUTH : <<include>>

@enduml