"""create_detection_tables

Revision ID: 008f802917b7
Revises: 9c1f3aa8cf1f
Create Date: 2026-03-14 16:29:34.686991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008f802917b7'
down_revision: Union[str, Sequence[str], None] = '9c1f3aa8cf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_anomaly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detector_votes', sa.String(length=200), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('stl_residual_zscore', sa.Float(), nullable=True),
    sa.Column('isolation_score', sa.Float(), nullable=True),
    sa.Column('cusum_value', sa.Float(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_std_dev', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_log_id', sa.UUID(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomaly_severity', 'llm_anomaly', ['severity'], unique=False)
    op.create_index('ix_anomaly_tenant_detected', 'llm_anomaly', ['tenant_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_llm_anomaly_detected_at'), 'llm_anomaly', ['detected_at'], unique=False)
    op.create_index(op.f('ix_llm_anomaly_tenant_id'), 'llm_anomaly', ['tenant_id'], unique=False)
    op.create_table('llm_token_baseline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('daily_mean', sa.Float(), nullable=False),
    sa.Column('daily_std_dev', sa.Float(), nullable=False),
    sa.Column('daily_min', sa.Float(), nullable=False),
    sa.Column('daily_max', sa.Float(), nullable=False),
    sa.Column('call_count_mean', sa.Float(), nullable=False),
    sa.Column('call_count_std_dev', sa.Float(), nullable=False),
    sa.Column('daily_cost_mean', sa.Float(), nullable=False),
    sa.Column('daily_cost_std_dev', sa.Float(), nullable=False),
    sa.Column('error_rate_mean', sa.Float(), nullable=False),
    sa.Column('cusum_pos', sa.Float(), nullable=False),
    sa.Column('cusum_neg', sa.Float(), nullable=False),
    sa.Column('cusum_k', sa.Float(), nullable=False),
    sa.Column('isolation_forest_threshold', sa.Float(), nullable=False),
    sa.Column('sample_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_token_baseline_tenant_id'), 'llm_token_baseline', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_token_baseline_tenant_id'), table_name='llm_token_baseline')
    op.drop_table('llm_token_baseline')
    op.drop_index(op.f('ix_llm_anomaly_tenant_id'), table_name='llm_anomaly')
    op.drop_index(op.f('ix_llm_anomaly_detected_at'), table_name='llm_anomaly')
    op.drop_index('ix_anomaly_tenant_detected', table_name='llm_anomaly')
    op.drop_index('ix_anomaly_severity', table_name='llm_anomaly')
    op.drop_table('llm_anomaly')
    # ### end Alembic commands ###
