"""add_m10_billing_tables

Revision ID: 290e34bcb733
Revises: 659a50ba3f82
Create Date: 2026-03-22 23:36:11.391076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '290e34bcb733'
down_revision: Union[str, Sequence[str], None] = '659a50ba3f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_billing_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_line_items_billing_id', 'llm_billing_line_items', ['billing_id'], unique=False)
    op.create_index('ix_line_items_tenant_month', 'llm_billing_line_items', ['tenant_id', 'year_month'], unique=False)
    op.create_index(op.f('ix_llm_billing_line_items_billing_id'), 'llm_billing_line_items', ['billing_id'], unique=False)
    op.create_table('llm_billing_monthly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('included_tokens', sa.BigInteger(), nullable=False),
    sa.Column('included_fee_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('overage_rate_per_1k_tokens', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('actual_total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('actual_total_calls', sa.BigInteger(), nullable=False),
    sa.Column('actual_raw_cost_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tokens_included_used', sa.BigInteger(), nullable=False),
    sa.Column('tokens_overage', sa.BigInteger(), nullable=False),
    sa.Column('overage_cost_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('discount_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_billed_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('margin_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year_month', name='uq_billing_tenant_month')
    )
    op.create_index('ix_billing_monthly_status', 'llm_billing_monthly', ['status'], unique=False)
    op.create_index('ix_billing_monthly_tenant', 'llm_billing_monthly', ['tenant_id'], unique=False)
    op.create_index('ix_billing_monthly_year_month', 'llm_billing_monthly', ['year_month'], unique=False)
    op.create_table('llm_client_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('json_summary', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_reports_tenant', 'llm_client_reports', ['tenant_id'], unique=False)
    op.create_index('ix_client_reports_year_month', 'llm_client_reports', ['year_month'], unique=False)
    # op.drop_index(op.f('ix_assistant_log_created'), table_name='llm_dashboard_assistant_log')
    # op.drop_index(op.f('ix_assistant_log_user'), table_name='llm_dashboard_assistant_log')
    # op.drop_table('llm_dashboard_assistant_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_dashboard_assistant_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), server_default=sa.text("'anonymous'::character varying"), autoincrement=False, nullable=False),
    sa.Column('question_preview', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tenant_scope', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('llm_model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_dashboard_assistant_log_pkey'))
    )
    op.create_index(op.f('ix_assistant_log_user'), 'llm_dashboard_assistant_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_assistant_log_created'), 'llm_dashboard_assistant_log', ['created_at'], unique=False)
    op.drop_index('ix_client_reports_year_month', table_name='llm_client_reports')
    op.drop_index('ix_client_reports_tenant', table_name='llm_client_reports')
    op.drop_table('llm_client_reports')
    op.drop_index('ix_billing_monthly_year_month', table_name='llm_billing_monthly')
    op.drop_index('ix_billing_monthly_tenant', table_name='llm_billing_monthly')
    op.drop_index('ix_billing_monthly_status', table_name='llm_billing_monthly')
    op.drop_table('llm_billing_monthly')
    op.drop_index(op.f('ix_llm_billing_line_items_billing_id'), table_name='llm_billing_line_items')
    op.drop_index('ix_line_items_tenant_month', table_name='llm_billing_line_items')
    op.drop_index('ix_line_items_billing_id', table_name='llm_billing_line_items')
    op.drop_table('llm_billing_line_items')
    # ### end Alembic commands ###
