"""add quality_score to llm_token_log

Revision ID: 3486c40e2bda
Revises: fd9649929be6
Create Date: 2026-04-04 23:20:43.139559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3486c40e2bda'
down_revision: Union[str, Sequence[str], None] = 'fd9649929be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_token_log', sa.Column('quality_score', sa.Float(), nullable=True, comment='Response quality score 0.0-1.0, populated by downstream evaluation. Used to train the M7 smart router.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_token_log', 'quality_score')
    # ### end Alembic commands ###
