"""create_optimizer_tables

Revision ID: 3d6596a42146
Revises: 9303943ad31f
Create Date: 2026-03-16 17:57:26.715736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6596a42146'
down_revision: Union[str, Sequence[str], None] = '9303943ad31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_model_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('current_model', sa.String(length=100), nullable=False),
    sa.Column('recommended_model', sa.String(length=100), nullable=False),
    sa.Column('justification_type', sa.String(length=30), nullable=False),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('avg_input_tokens', sa.Float(), nullable=False),
    sa.Column('avg_output_tokens', sa.Float(), nullable=False),
    sa.Column('avg_cost_per_call', sa.Float(), nullable=False),
    sa.Column('error_rate_pct', sa.Float(), nullable=False),
    sa.Column('monthly_call_count', sa.Integer(), nullable=False),
    sa.Column('current_monthly_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('projected_monthly_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('expected_monthly_saving_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('expected_saving_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', name='uq_model_rec_tenant_agent')
    )
    op.create_index('ix_model_rec_tenant', 'llm_model_recommendation', ['tenant_id'], unique=False)
    op.create_table('llm_prompt_optimization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('use_case', sa.String(length=100), nullable=False),
    sa.Column('optimization_type', sa.String(length=50), nullable=False),
    sa.Column('observed_avg_input_tokens', sa.Float(), nullable=False),
    sa.Column('observed_avg_output_tokens', sa.Float(), nullable=False),
    sa.Column('observed_call_count', sa.Integer(), nullable=False),
    sa.Column('recommendation_title', sa.String(length=200), nullable=False),
    sa.Column('recommendation_detail', sa.Text(), nullable=True),
    sa.Column('estimated_token_reduction_pct', sa.Float(), nullable=False),
    sa.Column('expected_token_saving_monthly', sa.Integer(), nullable=False),
    sa.Column('expected_cost_saving_monthly_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_opt_status', 'llm_prompt_optimization', ['status'], unique=False)
    op.create_index('ix_prompt_opt_tenant_agent', 'llm_prompt_optimization', ['tenant_id', 'agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_opt_tenant_agent', table_name='llm_prompt_optimization')
    op.drop_index('ix_prompt_opt_status', table_name='llm_prompt_optimization')
    op.drop_table('llm_prompt_optimization')
    op.drop_index('ix_model_rec_tenant', table_name='llm_model_recommendation')
    op.drop_table('llm_model_recommendation')
    # ### end Alembic commands ###
