"""Add tracking fields to LLMTokenLog

Revision ID: 3e14bdcb6d18
Revises: f71859b09d7f
Create Date: 2026-04-03 16:46:27.932900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e14bdcb6d18'
down_revision: Union[str, Sequence[str], None] = 'f71859b09d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_auth_users_tenant'), table_name='llm_auth_users')
    # op.drop_index(op.f('ix_auth_users_username'), table_name='llm_auth_users')
    # op.drop_table('llm_auth_users')
    op.add_column('llm_token_log', sa.Column('site_id', sa.String(length=100), nullable=True, comment='Physical or logical site identifier'))
    op.add_column('llm_token_log', sa.Column('module', sa.String(length=100), nullable=True, comment='Application module generating the call'))
    op.add_column('llm_token_log', sa.Column('pricing_profile', sa.String(length=100), nullable=True, comment='Pricing tier or contract profile applied'))
    op.create_index(op.f('ix_llm_token_log_module'), 'llm_token_log', ['module'], unique=False)
    op.create_index(op.f('ix_llm_token_log_site_id'), 'llm_token_log', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_token_log_site_id'), table_name='llm_token_log')
    op.drop_index(op.f('ix_llm_token_log_module'), table_name='llm_token_log')
    op.drop_column('llm_token_log', 'pricing_profile')
    op.drop_column('llm_token_log', 'module')
    op.drop_column('llm_token_log', 'site_id')
    op.create_table('llm_auth_users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), server_default=sa.text("'tenant_viewer'::character varying"), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_auth_users_pkey'))
    )
    op.create_index(op.f('ix_auth_users_username'), 'llm_auth_users', ['username'], unique=True)
    op.create_index(op.f('ix_auth_users_tenant'), 'llm_auth_users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
