"""create_gateway_tables

Revision ID: 56cf37e4ff76
Revises: 
Create Date: 2026-03-08 20:04:12.410852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56cf37e4ff76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_governance_rules',
    sa.Column('id', sa.UUID(), nullable=False, comment='Rule identifier'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='Type of rule: tenant_limit, model_block, budget_cap, etc.'),
    sa.Column('tenant_id', sa.String(length=100), nullable=True, comment='Target tenant. NULL means rule applies to all tenants.'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='Target model. NULL means rule applies to all models.'),
    sa.Column('daily_token_limit', sa.BigInteger(), nullable=True, comment='Maximum tokens allowed per day. NULL means no limit.'),
    sa.Column('monthly_token_limit', sa.BigInteger(), nullable=True, comment='Maximum tokens allowed per month. NULL means no limit.'),
    sa.Column('monthly_budget_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum spend in USD per month. NULL means no limit.'),
    sa.Column('max_tokens_per_request', sa.Integer(), nullable=True, comment='Maximum tokens allowed in a single request.'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority rules win when multiple rules match. Default 100.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Inactive rules are ignored without being deleted.'),
    sa.Column('downgrade_to_model', sa.String(length=100), nullable=True, comment='For MODEL_DOWNGRADE rules: substitute this model instead.'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='Rule is inactive before this UTC datetime.'),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True, comment='Rule is inactive after this UTC datetime.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable explanation of what this rule does.'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='Admin user who created this rule.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when rule was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when rule was last updated.'),
    sa.PrimaryKeyConstraint('id'),
    comment='Governance rules controlling tenant access and limits.'
    )
    op.create_index('ix_governance_rules_tenant_active', 'llm_governance_rules', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_governance_rules_type_active', 'llm_governance_rules', ['rule_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_llm_governance_rules_is_active'), 'llm_governance_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_llm_governance_rules_rule_type'), 'llm_governance_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_llm_governance_rules_tenant_id'), 'llm_governance_rules', ['tenant_id'], unique=False)
    op.create_table('llm_token_log',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique call identifier'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='External request ID from the API caller for correlation'),
    sa.Column('tenant_id', sa.String(length=100), nullable=False, comment='Tenant that made this call'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='Agent or service within the tenant that made the call'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='End user ID if available'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='LLM model name e.g. gpt-4o-mini, claude-3-haiku'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='LLM provider e.g. openai, anthropic, google'),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False, comment='Number of tokens in the prompt/input'),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False, comment='Number of tokens in the completion/output'),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False, comment='Total tokens = input + output'),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=False, comment='Cost in USD calculated at call time'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='End-to-end call duration in milliseconds'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Call outcome: success, error, timeout, blocked'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if status is error or timeout'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional call metadata as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the call — TimescaleDB partition key'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    comment='Core time-series table for all LLM API calls. Made a TimescaleDB hypertable during migration.'
    )
    op.create_index(op.f('ix_llm_token_log_agent_id'), 'llm_token_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_llm_token_log_created_at'), 'llm_token_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_token_log_model'), 'llm_token_log', ['model'], unique=False)
    op.create_index('ix_llm_token_log_model_created', 'llm_token_log', ['model', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_token_log_status'), 'llm_token_log', ['status'], unique=False)
    op.create_index('ix_llm_token_log_tenant_agent', 'llm_token_log', ['tenant_id', 'agent_id'], unique=False)
    op.create_index('ix_llm_token_log_tenant_created', 'llm_token_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_token_log_tenant_id'), 'llm_token_log', ['tenant_id'], unique=False)
    op.create_table('llm_governance_decisions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Decision identifier'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Correlates with llm_token_log.request_id'),
    sa.Column('tenant_id', sa.String(length=100), nullable=False, comment='Tenant whose call was evaluated'),
    sa.Column('model_requested', sa.String(length=100), nullable=False, comment='Model the tenant requested'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='Model actually used (differs from requested on ALLOW_DOWNGRADE)'),
    sa.Column('decision', sa.String(length=20), nullable=False, comment='Outcome: allow, allow_downgrade, block'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Human-readable reason for the decision'),
    sa.Column('rule_id', sa.UUID(), nullable=True, comment='Rule that triggered this decision. NULL if no rule matched.'),
    sa.Column('tokens_used_today', sa.BigInteger(), nullable=True, comment='Tenant token usage at time of decision (from Redis)'),
    sa.Column('budget_used_today', sa.Numeric(precision=10, scale=4), nullable=True, comment='Tenant cost at time of decision (from Redis)'),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when governance was evaluated'),
    sa.ForeignKeyConstraint(['rule_id'], ['llm_governance_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit log of all governance decisions.'
    )
    op.create_index('ix_governance_decisions_decision_evaluated', 'llm_governance_decisions', ['decision', 'evaluated_at'], unique=False)
    op.create_index('ix_governance_decisions_tenant_evaluated', 'llm_governance_decisions', ['tenant_id', 'evaluated_at'], unique=False)
    op.create_index(op.f('ix_llm_governance_decisions_decision'), 'llm_governance_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_llm_governance_decisions_evaluated_at'), 'llm_governance_decisions', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_llm_governance_decisions_request_id'), 'llm_governance_decisions', ['request_id'], unique=False)
    op.create_index(op.f('ix_llm_governance_decisions_tenant_id'), 'llm_governance_decisions', ['tenant_id'], unique=False)
    # Convert llm_token_log to a TimescaleDB hypertable
    op.execute(
        "SELECT create_hypertable('llm_token_log', 'created_at', "
        "chunk_time_interval => INTERVAL '7 days', "
        "if_not_exists => TRUE)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_governance_decisions_tenant_id'), table_name='llm_governance_decisions')
    op.drop_index(op.f('ix_llm_governance_decisions_request_id'), table_name='llm_governance_decisions')
    op.drop_index(op.f('ix_llm_governance_decisions_evaluated_at'), table_name='llm_governance_decisions')
    op.drop_index(op.f('ix_llm_governance_decisions_decision'), table_name='llm_governance_decisions')
    op.drop_index('ix_governance_decisions_tenant_evaluated', table_name='llm_governance_decisions')
    op.drop_index('ix_governance_decisions_decision_evaluated', table_name='llm_governance_decisions')
    op.drop_table('llm_governance_decisions')
    op.drop_index(op.f('ix_llm_token_log_tenant_id'), table_name='llm_token_log')
    op.drop_index('ix_llm_token_log_tenant_created', table_name='llm_token_log')
    op.drop_index('ix_llm_token_log_tenant_agent', table_name='llm_token_log')
    op.drop_index(op.f('ix_llm_token_log_status'), table_name='llm_token_log')
    op.drop_index('ix_llm_token_log_model_created', table_name='llm_token_log')
    op.drop_index(op.f('ix_llm_token_log_model'), table_name='llm_token_log')
    op.drop_index(op.f('ix_llm_token_log_created_at'), table_name='llm_token_log')
    op.drop_index(op.f('ix_llm_token_log_agent_id'), table_name='llm_token_log')
    op.drop_table('llm_token_log')
    op.drop_index(op.f('ix_llm_governance_rules_tenant_id'), table_name='llm_governance_rules')
    op.drop_index(op.f('ix_llm_governance_rules_rule_type'), table_name='llm_governance_rules')
    op.drop_index(op.f('ix_llm_governance_rules_is_active'), table_name='llm_governance_rules')
    op.drop_index('ix_governance_rules_type_active', table_name='llm_governance_rules')
    op.drop_index('ix_governance_rules_tenant_active', table_name='llm_governance_rules')
    op.drop_table('llm_governance_rules')
    # ### end Alembic commands ###
