"""add explainer and optimizer tables

Revision ID: 6fb178031d24
Revises: 449a6a770742
Create Date: 2026-04-23 21:19:44.494461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb178031d24'
down_revision: Union[str, Sequence[str], None] = '449a6a770742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_action'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_audit_log_resource_type'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='llm_audit_log')
    op.create_index(op.f('ix_llm_audit_log_action'), 'llm_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_resource_type'), 'llm_audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_tenant_id'), 'llm_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_user_id'), 'llm_audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_audit_log_user_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_tenant_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_resource_type'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_action'), table_name='llm_audit_log')
    op.create_index(op.f('ix_audit_log_user_id'), 'llm_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'llm_audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_type'), 'llm_audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'llm_audit_log', ['action'], unique=False)
    # ### end Alembic commands ###
