"""Add agent_id and model to Detection baseline

Revision ID: 8aa130b812be
Revises: 3e14bdcb6d18
Create Date: 2026-04-03 20:55:51.854612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa130b812be'
down_revision: Union[str, Sequence[str], None] = '3e14bdcb6d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_anomaly', sa.Column('agent_id', sa.String(length=100), nullable=False, server_default='*'))
    op.add_column('llm_anomaly', sa.Column('model', sa.String(length=100), nullable=False, server_default='*'))
    op.add_column('llm_token_baseline', sa.Column('agent_id', sa.String(length=100), nullable=False, server_default='*'))
    op.add_column('llm_token_baseline', sa.Column('model', sa.String(length=100), nullable=False, server_default='*'))
    op.drop_index(op.f('ix_llm_token_baseline_tenant_id'), table_name='llm_token_baseline')
    op.create_index(op.f('ix_llm_token_baseline_tenant_id'), 'llm_token_baseline', ['tenant_id'], unique=False)
    op.create_unique_constraint('uq_baseline_scope', 'llm_token_baseline', ['tenant_id', 'agent_id', 'model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_baseline_scope', 'llm_token_baseline', type_='unique')
    op.drop_index(op.f('ix_llm_token_baseline_tenant_id'), table_name='llm_token_baseline')
    op.create_index(op.f('ix_llm_token_baseline_tenant_id'), 'llm_token_baseline', ['tenant_id'], unique=True)
    op.drop_column('llm_token_baseline', 'model')
    op.drop_column('llm_token_baseline', 'agent_id')
    op.drop_column('llm_anomaly', 'model')
    op.drop_column('llm_anomaly', 'agent_id')
    # ### end Alembic commands ###
