"""create_explainer_tables

Revision ID: 9303943ad31f
Revises: c2444e579193
Create Date: 2026-03-16 17:17:58.278858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9303943ad31f'
down_revision: Union[str, Sequence[str], None] = 'c2444e579193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_token_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_id', name='uq_explanation_anomaly')
    )
    op.create_index(op.f('ix_llm_token_explanations_anomaly_id'), 'llm_token_explanations', ['anomaly_id'], unique=False)
    op.create_table('llm_token_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('explanation_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_title', sa.String(length=200), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('expected_token_saving', sa.Integer(), nullable=True),
    sa.Column('expected_cost_saving_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_token_recommendations_anomaly_id'), 'llm_token_recommendations', ['anomaly_id'], unique=False)
    op.create_index(op.f('ix_llm_token_recommendations_explanation_id'), 'llm_token_recommendations', ['explanation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_token_recommendations_explanation_id'), table_name='llm_token_recommendations')
    op.drop_index(op.f('ix_llm_token_recommendations_anomaly_id'), table_name='llm_token_recommendations')
    op.drop_table('llm_token_recommendations')
    op.drop_index(op.f('ix_llm_token_explanations_anomaly_id'), table_name='llm_token_explanations')
    op.drop_table('llm_token_explanations')
    # ### end Alembic commands ###
