"""Add trace_id to LLMTokenLog

Revision ID: 9469848792c8
Revises: 0f57e101896c
Create Date: 2026-04-15 18:58:46.862624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9469848792c8'
down_revision: Union[str, Sequence[str], None] = '0f57e101896c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_token_log', sa.Column('trace_id', sa.String(length=64), nullable=True, comment='Gateway-generated trace ID for end-to-end correlation across M1→M10'))
    op.create_index(op.f('ix_llm_token_log_trace_id'), 'llm_token_log', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_token_log_trace_id'), table_name='llm_token_log')
    op.drop_column('llm_token_log', 'trace_id')
    # ### end Alembic commands ###
