"""Add tenant and credential models

Revision ID: 9a1807efc5f9
Revises: c4d5e6f7a8b9
Create Date: 2026-05-02 12:57:29.425772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a1807efc5f9'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_tenant_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_tenant_credentials_tenant_id'), 'llm_tenant_credentials', ['tenant_id'], unique=False)
    op.alter_column('llm_alert_configs', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Channel name, e.g. '#ops-alerts' or 'PagerDuty Critical'",
               existing_nullable=False)
    op.alter_column('llm_alert_configs', 'channel_type',
               existing_type=sa.VARCHAR(length=20),
               comment='slack | teams | pagerduty | generic | email',
               existing_nullable=False)
    op.alter_column('llm_alert_configs', 'webhook_url',
               existing_type=sa.VARCHAR(length=500),
               comment='Webhook URL to POST alerts to',
               existing_nullable=False)
    op.alter_column('llm_alert_configs', 'alert_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Which alert types to receive: ['blocked', 'budget_exceeded', 'anomaly', 'fallback']",
               existing_nullable=True)
    op.alter_column('llm_alert_configs', 'severity_filter',
               existing_type=sa.VARCHAR(length=20),
               comment='Minimum severity: info | warning | error | critical',
               existing_nullable=True)
    op.create_index(op.f('ix_llm_alert_configs_tenant_id'), 'llm_alert_configs', ['tenant_id'], unique=False)
    op.alter_column('llm_alert_history', 'config_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to llm_alert_configs',
               existing_nullable=False)
    op.alter_column('llm_alert_history', 'alert_type',
               existing_type=sa.VARCHAR(length=50),
               comment='blocked | budget_exceeded | anomaly | fallback | test',
               existing_nullable=False)
    op.alter_column('llm_alert_history', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='The payload sent to the webhook (sensitive fields redacted)',
               existing_nullable=True)
    op.create_index(op.f('ix_llm_alert_history_tenant_id'), 'llm_alert_history', ['tenant_id'], unique=False)
    op.alter_column('llm_experiments', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Experiment name, e.g. 'Shorter summarization prompt'",
               existing_nullable=False)
    op.alter_column('llm_experiments', 'prompt_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Prompt template name being tested',
               existing_nullable=False)
    op.alter_column('llm_experiments', 'variant_a_version',
               existing_type=sa.INTEGER(),
               comment='Prompt version for control (A)',
               existing_nullable=False)
    op.alter_column('llm_experiments', 'variant_b_version',
               existing_type=sa.INTEGER(),
               comment='Prompt version for treatment (B)',
               existing_nullable=False)
    op.alter_column('llm_experiments', 'traffic_split',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Fraction of traffic routed to variant B (0.0-1.0)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('llm_experiments', 'primary_metric',
               existing_type=sa.VARCHAR(length=50),
               comment='Metric to compare: quality_score | latency | cost | error_rate',
               existing_nullable=False,
               existing_server_default=sa.text("'''quality_score'''::character varying"))
    op.alter_column('llm_experiments', 'winner',
               existing_type=sa.VARCHAR(length=1),
               comment="'A' or 'B' — set when significance is reached",
               existing_nullable=True)
    op.alter_column('llm_experiments', 'p_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Statistical p-value from the comparison test',
               existing_nullable=True)
    op.alter_column('llm_experiments', 'confidence_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence level (e.g., 0.95)',
               existing_nullable=True)
    op.alter_column('llm_experiments', 'min_samples',
               existing_type=sa.INTEGER(),
               comment='Minimum samples per variant before declaring a winner',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.create_index(op.f('ix_llm_experiments_tenant_id'), 'llm_experiments', ['tenant_id'], unique=False)
    op.alter_column('llm_prompt_templates', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Prompt identifier, e.g. 'summarize_report'. Unique per tenant.",
               existing_comment="Prompt identifier, e.g. 'summarize_report'",
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'slug',
               existing_type=sa.VARCHAR(length=200),
               comment="URL-safe version of name, e.g. 'summarize-report'",
               existing_comment='URL-safe version of name',
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'version',
               existing_type=sa.INTEGER(),
               comment='Auto-incrementing version number per (tenant_id, name)',
               existing_comment='Auto-incrementing version per (tenant_id, name)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('llm_prompt_templates', 'content',
               existing_type=sa.TEXT(),
               comment='The prompt template text with {{variable}} placeholders',
               existing_comment='Prompt template text with {{variable}} placeholders',
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'description',
               existing_type=sa.VARCHAR(length=1000),
               comment='Human-readable description of what this prompt does',
               existing_comment='What this prompt does',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'model',
               existing_type=sa.VARCHAR(length=100),
               comment="Preferred model for this prompt (e.g., 'gpt-4o-mini')",
               existing_comment='Preferred model for this prompt',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment='Max output tokens for this prompt',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Temperature setting (0.0-2.0)',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Categorization tags, e.g. ['finance', 'report', 'summarization']",
               existing_comment='Categorization tags',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Prompt status: draft | published | archived',
               existing_comment='draft | published | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('llm_prompt_templates', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='True if this version is the active/published one',
               existing_comment='True if this version is active/published',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('llm_prompt_templates', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this version was published',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'published_by',
               existing_type=sa.VARCHAR(length=36),
               comment='User ID who published this version',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               comment='User ID who created this version',
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'parent_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID of the previous version this was derived from',
               existing_comment='ID of the previous version',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'change_summary',
               existing_type=sa.VARCHAR(length=500),
               comment='What changed in this version (commit message)',
               existing_comment='What changed in this version',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               comment='Number of times this prompt version has been used',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_prompt_templates', 'avg_tokens',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Average token count when this prompt is rendered',
               existing_nullable=True)
    op.drop_index(op.f('ix_prompt_tenant'), table_name='llm_prompt_templates')
    op.create_index(op.f('ix_llm_prompt_templates_tenant_id'), 'llm_prompt_templates', ['tenant_id'], unique=False)
    op.alter_column('llm_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Client-provided session identifier for grouping calls',
               existing_comment='Client-provided session identifier',
               existing_nullable=False)
    op.alter_column('llm_sessions', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               comment='User who initiated this session',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'agent_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Agent/pipeline that owns this session',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Human-readable session name, e.g. 'Report Generation Pipeline'",
               existing_nullable=True)
    op.alter_column('llm_sessions', 'total_calls',
               existing_type=sa.INTEGER(),
               comment='Total number of LLM calls in this session',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_sessions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Arbitrary session metadata',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'call_chain',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered list of LLMTokenLog IDs in this session',
               existing_nullable=True)
    op.create_index(op.f('ix_llm_sessions_tenant_id'), 'llm_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_llm_virtual_keys_tenant_id'), 'llm_virtual_keys', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'llm_virtual_keys', ['key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_virtual_keys', type_='unique')
    op.drop_index(op.f('ix_llm_virtual_keys_tenant_id'), table_name='llm_virtual_keys')
    op.drop_index(op.f('ix_llm_sessions_tenant_id'), table_name='llm_sessions')
    op.alter_column('llm_sessions', 'call_chain',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered list of LLMTokenLog IDs in this session',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Arbitrary session metadata',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'total_calls',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total number of LLM calls in this session',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_sessions', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Human-readable session name, e.g. 'Report Generation Pipeline'",
               existing_nullable=True)
    op.alter_column('llm_sessions', 'agent_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Agent/pipeline that owns this session',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='User who initiated this session',
               existing_nullable=True)
    op.alter_column('llm_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Client-provided session identifier',
               existing_comment='Client-provided session identifier for grouping calls',
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_prompt_templates_tenant_id'), table_name='llm_prompt_templates')
    op.create_index(op.f('ix_prompt_tenant'), 'llm_prompt_templates', ['tenant_id'], unique=False)
    op.alter_column('llm_prompt_templates', 'avg_tokens',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Average token count when this prompt is rendered',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'usage_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of times this prompt version has been used',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_prompt_templates', 'change_summary',
               existing_type=sa.VARCHAR(length=500),
               comment='What changed in this version',
               existing_comment='What changed in this version (commit message)',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'parent_version_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID of the previous version',
               existing_comment='ID of the previous version this was derived from',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='User ID who created this version',
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'published_by',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='User ID who published this version',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this version was published',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='True if this version is active/published',
               existing_comment='True if this version is the active/published one',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('llm_prompt_templates', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='draft | published | archived',
               existing_comment='Prompt status: draft | published | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('llm_prompt_templates', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Categorization tags',
               existing_comment="Categorization tags, e.g. ['finance', 'report', 'summarization']",
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Temperature setting (0.0-2.0)',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Max output tokens for this prompt',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'model',
               existing_type=sa.VARCHAR(length=100),
               comment='Preferred model for this prompt',
               existing_comment="Preferred model for this prompt (e.g., 'gpt-4o-mini')",
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'description',
               existing_type=sa.VARCHAR(length=1000),
               comment='What this prompt does',
               existing_comment='Human-readable description of what this prompt does',
               existing_nullable=True)
    op.alter_column('llm_prompt_templates', 'content',
               existing_type=sa.TEXT(),
               comment='Prompt template text with {{variable}} placeholders',
               existing_comment='The prompt template text with {{variable}} placeholders',
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'version',
               existing_type=sa.INTEGER(),
               comment='Auto-incrementing version per (tenant_id, name)',
               existing_comment='Auto-incrementing version number per (tenant_id, name)',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('llm_prompt_templates', 'slug',
               existing_type=sa.VARCHAR(length=200),
               comment='URL-safe version of name',
               existing_comment="URL-safe version of name, e.g. 'summarize-report'",
               existing_nullable=False)
    op.alter_column('llm_prompt_templates', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment="Prompt identifier, e.g. 'summarize_report'",
               existing_comment="Prompt identifier, e.g. 'summarize_report'. Unique per tenant.",
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_experiments_tenant_id'), table_name='llm_experiments')
    op.alter_column('llm_experiments', 'min_samples',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Minimum samples per variant before declaring a winner',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('llm_experiments', 'confidence_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence level (e.g., 0.95)',
               existing_nullable=True)
    op.alter_column('llm_experiments', 'p_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Statistical p-value from the comparison test',
               existing_nullable=True)
    op.alter_column('llm_experiments', 'winner',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment="'A' or 'B' — set when significance is reached",
               existing_nullable=True)
    op.alter_column('llm_experiments', 'primary_metric',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Metric to compare: quality_score | latency | cost | error_rate',
               existing_nullable=False,
               existing_server_default=sa.text("'''quality_score'''::character varying"))
    op.alter_column('llm_experiments', 'traffic_split',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Fraction of traffic routed to variant B (0.0-1.0)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('llm_experiments', 'variant_b_version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Prompt version for treatment (B)',
               existing_nullable=False)
    op.alter_column('llm_experiments', 'variant_a_version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Prompt version for control (A)',
               existing_nullable=False)
    op.alter_column('llm_experiments', 'prompt_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Prompt template name being tested',
               existing_nullable=False)
    op.alter_column('llm_experiments', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Experiment name, e.g. 'Shorter summarization prompt'",
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_alert_history_tenant_id'), table_name='llm_alert_history')
    op.alter_column('llm_alert_history', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='The payload sent to the webhook (sensitive fields redacted)',
               existing_nullable=True)
    op.alter_column('llm_alert_history', 'alert_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='blocked | budget_exceeded | anomaly | fallback | test',
               existing_nullable=False)
    op.alter_column('llm_alert_history', 'config_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='FK to llm_alert_configs',
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_alert_configs_tenant_id'), table_name='llm_alert_configs')
    op.alter_column('llm_alert_configs', 'severity_filter',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Minimum severity: info | warning | error | critical',
               existing_nullable=True)
    op.alter_column('llm_alert_configs', 'alert_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="Which alert types to receive: ['blocked', 'budget_exceeded', 'anomaly', 'fallback']",
               existing_nullable=True)
    op.alter_column('llm_alert_configs', 'webhook_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Webhook URL to POST alerts to',
               existing_nullable=False)
    op.alter_column('llm_alert_configs', 'channel_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='slack | teams | pagerduty | generic | email',
               existing_nullable=False)
    op.alter_column('llm_alert_configs', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Channel name, e.g. '#ops-alerts' or 'PagerDuty Critical'",
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_tenant_credentials_tenant_id'), table_name='llm_tenant_credentials')
    op.drop_table('llm_tenant_credentials')
    # ### end Alembic commands ###
