"""verify_billing_models

Revision ID: 9ad42406b81f
Revises: 290e34bcb733
Create Date: 2026-03-22 23:44:04.624041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ad42406b81f'
down_revision: Union[str, Sequence[str], None] = '290e34bcb733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_assistant_log_created'), table_name='llm_dashboard_assistant_log')
    # op.drop_index(op.f('ix_assistant_log_user'), table_name='llm_dashboard_assistant_log')
    # op.drop_table('llm_dashboard_assistant_log')
    op.add_column('llm_billing_line_items', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('llm_billing_line_items', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('llm_billing_line_items', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.add_column('llm_billing_line_items', sa.Column('quantity_tokens', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_line_items', sa.Column('quantity_calls', sa.Integer(), nullable=False))
    op.alter_column('llm_billing_line_items', 'line_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('llm_billing_line_items', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('llm_billing_line_items', 'unit_price_usd',
               existing_type=sa.NUMERIC(precision=14, scale=8),
               type_=sa.Numeric(precision=12, scale=8),
               existing_nullable=False)
    op.drop_column('llm_billing_line_items', 'sort_order')
    op.drop_column('llm_billing_line_items', 'unit')
    op.drop_column('llm_billing_line_items', 'quantity')
    op.add_column('llm_billing_monthly', sa.Column('total_calls', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('total_tokens', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('total_input_tokens', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('total_output_tokens', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('raw_cost_usd', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('forfait_tokens_included', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('forfait_tokens_used', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('overage_tokens', sa.BigInteger(), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('base_fee_usd', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('overage_charge_usd', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('credits_usd', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('snapshot_taken_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('llm_billing_monthly', sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('llm_billing_monthly', 'actual_total_calls')
    op.drop_column('llm_billing_monthly', 'overage_rate_per_1k_tokens')
    op.drop_column('llm_billing_monthly', 'included_tokens')
    op.drop_column('llm_billing_monthly', 'tokens_overage')
    op.drop_column('llm_billing_monthly', 'discount_usd')
    op.drop_column('llm_billing_monthly', 'contract_type')
    op.drop_column('llm_billing_monthly', 'included_fee_usd')
    op.drop_column('llm_billing_monthly', 'actual_raw_cost_usd')
    op.drop_column('llm_billing_monthly', 'margin_usd')
    op.drop_column('llm_billing_monthly', 'margin_pct')
    op.drop_column('llm_billing_monthly', 'overage_cost_usd')
    op.drop_column('llm_billing_monthly', 'tokens_included_used')
    op.drop_column('llm_billing_monthly', 'actual_total_tokens')
    op.drop_column('llm_billing_monthly', 'frozen_at')
    op.drop_column('llm_billing_monthly', 'updated_at')
    op.add_column('llm_client_reports', sa.Column('report_title', sa.String(length=300), nullable=False))
    op.add_column('llm_client_reports', sa.Column('executive_summary', sa.Text(), nullable=True))
    op.add_column('llm_client_reports', sa.Column('report_data', sa.Text(), nullable=True))
    op.alter_column('llm_client_reports', 'billing_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_report_tenant_month', 'llm_client_reports', ['tenant_id', 'year_month'])
    op.drop_column('llm_client_reports', 'pdf_path')
    op.drop_column('llm_client_reports', 'json_summary')
    op.drop_column('llm_client_reports', 'report_version')
    op.drop_column('llm_client_reports', 'sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_client_reports', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('llm_client_reports', sa.Column('report_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('llm_client_reports', sa.Column('json_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('llm_client_reports', sa.Column('pdf_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint('uq_report_tenant_month', 'llm_client_reports', type_='unique')
    op.alter_column('llm_client_reports', 'billing_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('llm_client_reports', 'report_data')
    op.drop_column('llm_client_reports', 'executive_summary')
    op.drop_column('llm_client_reports', 'report_title')
    op.add_column('llm_billing_monthly', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('llm_billing_monthly', sa.Column('frozen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('llm_billing_monthly', sa.Column('actual_total_tokens', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('tokens_included_used', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('overage_cost_usd', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('margin_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('margin_usd', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('actual_raw_cost_usd', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('included_fee_usd', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('contract_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('discount_usd', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('tokens_overage', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('included_tokens', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('overage_rate_per_1k_tokens', sa.NUMERIC(precision=12, scale=8), autoincrement=False, nullable=False))
    op.add_column('llm_billing_monthly', sa.Column('actual_total_calls', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('llm_billing_monthly', 'finalized_at')
    op.drop_column('llm_billing_monthly', 'snapshot_taken_at')
    op.drop_column('llm_billing_monthly', 'credits_usd')
    op.drop_column('llm_billing_monthly', 'overage_charge_usd')
    op.drop_column('llm_billing_monthly', 'base_fee_usd')
    op.drop_column('llm_billing_monthly', 'overage_tokens')
    op.drop_column('llm_billing_monthly', 'forfait_tokens_used')
    op.drop_column('llm_billing_monthly', 'forfait_tokens_included')
    op.drop_column('llm_billing_monthly', 'raw_cost_usd')
    op.drop_column('llm_billing_monthly', 'total_output_tokens')
    op.drop_column('llm_billing_monthly', 'total_input_tokens')
    op.drop_column('llm_billing_monthly', 'total_tokens')
    op.drop_column('llm_billing_monthly', 'total_calls')
    op.add_column('llm_billing_line_items', sa.Column('quantity', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False))
    op.add_column('llm_billing_line_items', sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('llm_billing_line_items', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('llm_billing_line_items', 'unit_price_usd',
               existing_type=sa.Numeric(precision=12, scale=8),
               type_=sa.NUMERIC(precision=14, scale=8),
               existing_nullable=False)
    op.alter_column('llm_billing_line_items', 'description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('llm_billing_line_items', 'line_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('llm_billing_line_items', 'quantity_calls')
    op.drop_column('llm_billing_line_items', 'quantity_tokens')
    op.drop_column('llm_billing_line_items', 'agent_id')
    op.drop_column('llm_billing_line_items', 'provider')
    op.drop_column('llm_billing_line_items', 'model')
    op.create_table('llm_dashboard_assistant_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), server_default=sa.text("'anonymous'::character varying"), autoincrement=False, nullable=False),
    sa.Column('question_preview', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tenant_scope', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('llm_model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_dashboard_assistant_log_pkey'))
    )
    op.create_index(op.f('ix_assistant_log_user'), 'llm_dashboard_assistant_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_assistant_log_created'), 'llm_dashboard_assistant_log', ['created_at'], unique=False)
    # ### end Alembic commands ###
