"""create_analytics_tables

Revision ID: 9c1f3aa8cf1f
Revises: 56cf37e4ff76
Create Date: 2026-03-14 15:50:34.354232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1f3aa8cf1f'
down_revision: Union[str, Sequence[str], None] = '56cf37e4ff76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cost_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calls', sa.BigInteger(), nullable=False),
    sa.Column('successful_calls', sa.BigInteger(), nullable=False),
    sa.Column('failed_calls', sa.BigInteger(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('top_model', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_cost_daily_tenant_date')
    )
    op.create_index('ix_cost_daily_date', 'llm_cost_daily', ['date'], unique=False)
    op.create_index('ix_cost_daily_tenant_date', 'llm_cost_daily', ['tenant_id', 'date'], unique=False)
    op.create_table('llm_cost_monthly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.BigInteger(), nullable=False),
    sa.Column('successful_calls', sa.BigInteger(), nullable=False),
    sa.Column('failed_calls', sa.BigInteger(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('cost_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tokens_change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year_month', name='uq_cost_monthly_tenant_month')
    )
    op.create_index('ix_cost_monthly_tenant_month', 'llm_cost_monthly', ['tenant_id', 'year_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cost_monthly_tenant_month', table_name='llm_cost_monthly')
    op.drop_table('llm_cost_monthly')
    op.drop_index('ix_cost_daily_tenant_date', table_name='llm_cost_daily')
    op.drop_index('ix_cost_daily_date', table_name='llm_cost_daily')
    op.drop_table('llm_cost_daily')
    # ### end Alembic commands ###
