"""add_last_activity_at_to_user

Revision ID: a240807108b8
Revises: 9a1807efc5f9
Create Date: 2026-05-02 13:13:45.040766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a240807108b8'
down_revision: Union[str, Sequence[str], None] = '9a1807efc5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_auth_users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_auth_users', 'last_activity_at')
    # ### end Alembic commands ###
