"""add_llm_pricing_rules

Revision ID: a58e5e539f77
Revises: 3d6596a42146
Create Date: 2026-03-17 17:37:43.164810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58e5e539f77'
down_revision: Union[str, Sequence[str], None] = '3d6596a42146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_price_per_1k', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('output_price_per_1k', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_effective_from', 'llm_pricing_rules', ['effective_from'], unique=False)
    op.create_index('ix_pricing_provider_model', 'llm_pricing_rules', ['provider', 'model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricing_provider_model', table_name='llm_pricing_rules')
    op.drop_index('ix_pricing_effective_from', table_name='llm_pricing_rules')
    op.drop_table('llm_pricing_rules')
    # ### end Alembic commands ###
