"""create_forecasting_tables

Revision ID: c2444e579193
Revises: 008f802917b7
Create Date: 2026-03-14 17:27:23.878436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2444e579193'
down_revision: Union[str, Sequence[str], None] = '008f802917b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_budget_risk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('risk_type', sa.String(length=30), nullable=False),
    sa.Column('days_until_exhaustion', sa.Integer(), nullable=False),
    sa.Column('exhaustion_date', sa.Date(), nullable=False),
    sa.Column('forecasted_value_at_exhaustion', sa.Float(), nullable=False),
    sa.Column('governance_limit', sa.Float(), nullable=False),
    sa.Column('pct_of_limit_today', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'risk_type', name='uq_budget_risk_tenant_type')
    )
    op.create_index(op.f('ix_llm_budget_risk_tenant_id'), 'llm_budget_risk', ['tenant_id'], unique=False)
    op.create_table('llm_forecast',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('predicted_tokens', sa.Float(), nullable=False),
    sa.Column('predicted_cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('trend_value', sa.Float(), nullable=True),
    sa.Column('seasonal_multiplier', sa.Float(), nullable=True),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'forecast_date', 'scenario', name='uq_forecast_tenant_date_scenario')
    )
    op.create_index('ix_forecast_generated', 'llm_forecast', ['generated_at'], unique=False)
    op.create_index('ix_forecast_tenant_date', 'llm_forecast', ['tenant_id', 'forecast_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecast_tenant_date', table_name='llm_forecast')
    op.drop_index('ix_forecast_generated', table_name='llm_forecast')
    op.drop_table('llm_forecast')
    op.drop_index(op.f('ix_llm_budget_risk_tenant_id'), table_name='llm_budget_risk')
    op.drop_table('llm_budget_risk')
    # ### end Alembic commands ###
