"""add prompt versioning and opt vectors

Revision ID: f5ac64edf4f7
Revises: c546839a6fda
Create Date: 2026-04-04 18:09:27.061237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f5ac64edf4f7'
down_revision: Union[str, Sequence[str], None] = 'c546839a6fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_prompt_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_ver_tenant_agent', 'llm_prompt_version', ['tenant_id', 'agent_id'], unique=False)
    op.add_column('llm_prompt_optimization', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_prompt_optimization', 'embedding')
    op.drop_index('ix_prompt_ver_tenant_agent', table_name='llm_prompt_version')
    op.drop_table('llm_prompt_version')
    # ### end Alembic commands ###
