"""add agent_id to llm_forecast

Revision ID: fd9649929be6
Revises: f5ac64edf4f7
Create Date: 2026-04-04 23:12:06.841926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9649929be6'
down_revision: Union[str, Sequence[str], None] = 'f5ac64edf4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable first (existing rows have no value)
    op.add_column('llm_forecast', sa.Column('agent_id', sa.String(length=100), nullable=True, server_default='*'))
    
    # Step 2: Backfill existing rows
    op.execute("UPDATE llm_forecast SET agent_id = '*' WHERE agent_id IS NULL")
    
    # Step 3: Set NOT NULL
    op.alter_column('llm_forecast', 'agent_id', nullable=False)
    
    # Step 4: Drop old constraints/indexes, create new ones
    op.drop_index(op.f('ix_forecast_tenant_date'), table_name='llm_forecast')
    op.drop_constraint(op.f('uq_forecast_tenant_date_scenario'), 'llm_forecast', type_='unique')
    op.create_index('ix_forecast_tenant_agent_date', 'llm_forecast', ['tenant_id', 'agent_id', 'forecast_date'], unique=False)
    op.create_unique_constraint('uq_forecast_tenant_agent_date_scenario', 'llm_forecast', ['tenant_id', 'agent_id', 'forecast_date', 'scenario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_forecast_tenant_agent_date_scenario', 'llm_forecast', type_='unique')
    op.drop_index('ix_forecast_tenant_agent_date', table_name='llm_forecast')
    op.create_unique_constraint(op.f('uq_forecast_tenant_date_scenario'), 'llm_forecast', ['tenant_id', 'forecast_date', 'scenario'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_forecast_tenant_date'), 'llm_forecast', ['tenant_id', 'forecast_date'], unique=False)
    op.drop_column('llm_forecast', 'agent_id')
    # ### end Alembic commands ###
