"""
M4 Explainer — database models.

Two tables per the architecture spec:
  llm_token_explanations  — one LLM-generated explanation per anomaly
  llm_token_recommendations — actionable recommendations linked to each explanation

Design principles:
- One explanation per anomaly (unique constraint on anomaly_id)
- Multiple recommendations per explanation (1-to-many)
- Tracks token cost of each LLM call (M4 must monitor its own consumption)
- Caching at the service layer (Redis) prevents duplicate LLM calls
"""

import uuid
from datetime import datetime, timezone
from decimal import Decimal

from sqlalchemy import (
    Boolean, DateTime, Float, ForeignKey,
    Integer, Numeric, String, Text, UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from pgvector.sqlalchemy import Vector

from core.database import Base


class LLMTokenExplanation(Base):
    """
    LLM-generated explanation for one detected anomaly.

    Generated by M4 when M3 detects an anomaly with severity
    >= WARNING. Triggered by the anomaly.detected event.

    confidence_level: how confident the LLM is in its explanation
        (0.0 = uncertain, 1.0 = confident). Derived from the
        model's self-reported confidence in the structured output.

    tokens_used: input + output tokens consumed by this explanation call.
        Tracked so M4's own consumption is visible in the dashboard.

    cache_hit: True if this explanation was served from Redis cache
        (no LLM call was made). False if a real LLM call was made.
    """

    __tablename__ = "llm_token_explanations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    anomaly_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    tenant_id: Mapped[str] = mapped_column(String(100), nullable=False)
    anomaly_type: Mapped[str] = mapped_column(String(50), nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)

    # The explanation text produced by the LLM
    explanation_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Metadata about the LLM call
    llm_model_used: Mapped[str] = mapped_column(String(100), nullable=False)
    tokens_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    confidence_level: Mapped[float] = mapped_column(Float, nullable=False, default=0.8)
    cache_hit: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    
    embedding: Mapped[list[float]] = mapped_column(
        Vector(384), nullable=True
    )

    __table_args__ = (
        UniqueConstraint("anomaly_id", name="uq_explanation_anomaly"),
    )


class LLMTokenRecommendation(Base):
    """
    One actionable recommendation linked to an explanation.

    Each explanation generates 2-4 recommendations ranked by impact.

    action_type: category of the recommendation
        technical    — change model, reduce prompt, add cache
        functional   — adjust frequency, review workflow
        financial    — set budget cap, enable downgrade rule
        governance   — add quota rule, require manual approval

    status lifecycle: proposed → applied / rejected
        proposed: default state when created
        applied: a human or automated rule acted on this
        rejected: reviewed and decided not to act

    expected_token_saving / expected_cost_saving:
        Estimated impact if this recommendation is applied.
        Used to prioritize: show highest-impact first.

    priority: 1 (highest) to 5 (lowest)
    """

    __tablename__ = "llm_token_recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    explanation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    anomaly_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    tenant_id: Mapped[str] = mapped_column(String(100), nullable=False)

    # What to do
    action_type: Mapped[str] = mapped_column(String(30), nullable=False)
    # technical / functional / financial / governance

    action_title: Mapped[str] = mapped_column(String(200), nullable=False)
    action_description: Mapped[str] = mapped_column(Text, nullable=True)

    # Expected impact
    expected_token_saving: Mapped[int] = mapped_column(Integer, nullable=True)
    expected_cost_saving_usd: Mapped[Decimal] = mapped_column(
        Numeric(precision=10, scale=4), nullable=True
    )
    risk_level: Mapped[str] = mapped_column(
        String(20), nullable=False, default="low"
    )
    # low / medium / high

    # Lifecycle
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="proposed"
    )
    # proposed / applied / rejected

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )